version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: thienhai
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: travel
    ports:
      - "5555:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
